name: Node.js Versions

on:
  workflow_dispatch:

jobs:
  node-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Node.js versions
        run: |
          echo "Installed Node.js versions:"
          ls /usr/local/lib/nodejs
