name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: eBPF Firewall
        id: test-action
        uses: lawrencegripper/actions-dns-monitoring@main
        with:
          milliseconds: 2000
        env:
          BLOCK_LIST: 'example.com,1.1.1.1'

      - name: Example npm build
        id: npm-build
        run: npm install

      - name: Test Curl example.com
        id: test-curl-1
        run: |
          curl --max-time 5 example.com || true
          curl --max-time 5 1.1.1.1

      - name: Test Curl bing.com
        id: test-curl-3
        run: curl bing.com
